// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8tqDQ00RzgEoHfIYhfczBbsoxmlra-UI',
    appId: '1:249509612490:web:1a761d9b7f86460b14dd33',
    messagingSenderId: '249509612490',
    projectId: 'fiverr-b12a9',
    authDomain: 'fiverr-b12a9.firebaseapp.com',
    storageBucket: 'fiverr-b12a9.appspot.com',
    measurementId: 'G-VB3ZV1QWSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMshhpr2KNRVW2ws4bMl2dOot3yvXhEU',
    appId: '1:249509612490:android:415bf03a8ebc92b014dd33',
    messagingSenderId: '249509612490',
    projectId: 'fiverr-b12a9',
    storageBucket: 'fiverr-b12a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_2NJJqukgU08ktmxvColJIIpvY1wPil0',
    appId: '1:249509612490:ios:83802e6ba9e8cc3a14dd33',
    messagingSenderId: '249509612490',
    projectId: 'fiverr-b12a9',
    storageBucket: 'fiverr-b12a9.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_2NJJqukgU08ktmxvColJIIpvY1wPil0',
    appId: '1:249509612490:ios:83802e6ba9e8cc3a14dd33',
    messagingSenderId: '249509612490',
    projectId: 'fiverr-b12a9',
    storageBucket: 'fiverr-b12a9.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8tqDQ00RzgEoHfIYhfczBbsoxmlra-UI',
    appId: '1:249509612490:web:c5d2b8d21e919a5d14dd33',
    messagingSenderId: '249509612490',
    projectId: 'fiverr-b12a9',
    authDomain: 'fiverr-b12a9.firebaseapp.com',
    storageBucket: 'fiverr-b12a9.appspot.com',
    measurementId: 'G-RSQQXFLYT0',
  );

}